use build action

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -66,13 +66,6 @@ jobs:
         with:
           ref: ${{ inputs.ref || github.ref }}
       -
-        name: Parse base image
-        id: base-image
-        run: |
-          BASE_IMAGE=$(cat smart-switches/build.yaml | yq '.build_from["${{ matrix.architecture }}"]')
-
-          echo "image=$BASE_IMAGE" | tee -a "$GITHUB_OUTPUT"
-      -
         name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
@@ -195,21 +188,37 @@ jobs:
         run: |
           exit 1
       -
-        name: docker build
+        name: Docker build flags
+        id: flags
         run: |
-          docker run \
-            --rm \
-            --privileged \
-            -v $(pwd)/smart-switches:/data \
-            -v /var/run/docker.sock:/var/run/docker.sock:ro \
-            ghcr.io/home-assistant/amd64-builder:latest \
-            --target smart-switches \
-            --image "smart-switches-{arch}" \
-            --addon \
-            --${{ matrix.architecture }} \
-            ${{ inputs.push && '' || '--no-latest ' }} \
-            --cache-tag ${{ github.ref }} \
-            --version "pr${{ github.event.number }}" \
-            -r ${{ github.server_url }}/${{ github.repository }} \
-            -b ${{ github.head_ref || github.ref_name }} \
-            -d "ghcr.io/${{ github.repository }}"
+          from=$(yq --no-colors eval ".build_from.${{ matrix.architecture }}" "smart-switches/build.yaml")
+          echo "from=${from}" | tee -a "$GITHUB_OUTPUT"
+
+          if [[ "${{ matrix.architecture}}" = "amd64" ]]; then
+            echo "platform=linux/amd64" | tee -a "$GITHUB_OUTPUT"
+          elif [[ "${{ matrix.architecture }}" = "i386" ]]; then
+            echo "platform=linux/386" | tee -a "$GITHUB_OUTPUT"
+          elif [[ "${{ matrix.architecture }}" = "armhf" ]]; then
+            echo "platform=linux/arm/v6" | tee -a "$GITHUB_OUTPUT"
+          elif [[ "${{ matrix.architecture }}" = "armv7" ]]; then
+            echo "platform=linux/arm/v7" | tee -a "$GITHUB_OUTPUT"
+          elif [[ "${{ matrix.architecture }}" = "aarch64" ]]; then
+            echo "platform=linux/arm64/v8 | tee -a "$GITHUB_OUTPUT"
+          else
+            echo "::error ::Could not determine platform for architecture ${{ matrix.architecture }}"
+            exit 1
+      -
+        name: docker build
+        uses: docker/build-push-action@v6.16.0
+        with:
+          push: false
+          context: smart-switches
+          file: smart-switches/Dockerfile
+          cache-from: |
+            type=local,src=/tmp/.docker-cache
+            ghcr.io/${{ github.repository }}/smart-switches/${{ matrix.architecture }}:edge
+          cache-to: type=local,mode=max,dest=/tmp/.docker-cache-new
+          platforms: ${{ steps.flags.outputs.platform }}
+          build-args: |
+            BUILD_ARCH=${{ matrix.architecture }}
+            BUILD_FROM=${{ steps.flags.outputs.from }}
